
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Feb 23 13:18:15 CET 2022
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
    public static final int EOF = 0;
  public static final int IDEN = 4;
  public static final int ENT = 5;
  public static final int REAL = 6;
  public static final int MAS = 7;
  public static final int MENOS = 8;
  public static final int POR = 9;
  public static final int DIV = 10;
  public static final int IGUAL = 11;
  public static final int COMA = 12;
  public static final int PAP = 13;
  public static final int PCIERRE = 14;
  public static final int CORCHETEAPERTURA=15;
  public static final int CORCHETECIERRE=16;
  public static final int PUNTO=17;
  public static final int WH=18;
  public static final int FOR=19;
  public static final int SI=20;
  public static final int SINO=21;
  public static final int HAZ=22;
  public static final int MIENTRAS=23;
  public static final int DEV=24;
  public static final int TENT=25;
  public static final int TBOOL=26;
  public static final int TDEC=27;
  public static final int PUNTOCOMA=28;
  public static final int MAYOR=29;
  public static final int MENOR=30;
  public static final int IGIGUAL=31;
  public static final int INCREMENTO=32;
  public static final int DECREMENTO=33;
}

